import os
BOT_TOKEN=os.getenv("BOT_TOKEN","")
DATABASE_PATH=os.getenv("DATABASE_PATH","strongfire.db")
TURN_SECONDS=30
STARTING_HP=200
MIN_DAMAGE=15
MAX_DAMAGE=40
WIN_REWARD=20
LOSS_REWARD=5
OWNER_ID=int(os.getenv("OWNER_ID","0"))
